// evms-training/src/components/ScenarioCard.svelte
<script>
	let {
		scenario,
		unlocked = false,
		completed = false,
		onSelect
	} = $props();
</script>

<button
	class="card"
	class:unlocked
	class:completed
	class:locked={!unlocked}
	onclick={() => unlocked && onSelect?.()}
	disabled={!unlocked}
	aria-disabled={!unlocked}
>
	<div class="difficulty">Level {scenario.difficulty}</div>
	<h4 class="title">{scenario.title}</h4>
	<p class="subtitle">{scenario.subtitle}</p>
	<div class="meta">
		<span>BAC: ${scenario.bac.toLocaleString()}</span>
		<span>•</span>
		<span>{scenario.duration}</span>
	</div>
	{#if completed}
		<span class="badge completed">Complete</span>
	{:else if !unlocked}
		<span class="badge locked">Locked</span>
	{/if}
</button>

<style>
	.card {
		position: relative;
		text-align: left;
		padding: var(--space-4);
		background: var(--surface-2);
		border: 2px solid var(--border);
		border-radius: var(--radius-lg);
		cursor: pointer;
		transition: all 0.2s ease;
		width: 100%;
	}

	.card:hover:not(:disabled) {
		border-color: var(--accent);
		transform: translateY(-2px);
		box-shadow: var(--shadow-md);
	}

	.card:disabled {
		cursor: not-allowed;
		opacity: 0.6;
	}

	.card.locked {
		filter: grayscale(0.3);
	}

	.card.completed {
		border-color: var(--success);
		background: var(--success-muted);
	}

	.difficulty {
		font-size: var(--text-xs);
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.05em;
		color: var(--accent);
		margin-bottom: var(--space-1);
	}

	.title {
		margin: 0 0 var(--space-1);
		font-size: var(--text-lg);
		font-weight: 700;
		color: var(--text-1);
	}

	.subtitle {
		margin: 0 0 var(--space-2);
		font-size: var(--text-sm);
		color: var(--text-2);
		line-height: 1.4;
	}

	.meta {
		font-size: var(--text-xs);
		color: var(--text-3);
		display: flex;
		gap: var(--space-2);
		flex-wrap: wrap;
	}

	.badge {
		position: absolute;
		top: var(--space-3);
		right: var(--space-3);
		font-size: var(--text-xs);
		font-weight: 600;
		padding: var(--space-1) var(--space-2);
		border-radius: var(--radius);
	}

	.badge.completed {
		background: var(--success);
		color: white;
	}

	.badge.locked {
		background: var(--surface-3);
		color: var(--text-3);
	}
</style>

// evms-training/components/interactive/ScenarioCard.tsx
'use client';

export function ScenarioCard({
	scenario,
	unlocked,
	completed,
	onSelect
}: {
	scenario: {
		id: number;
		title: string;
		subtitle: string;
		bac: number;
		duration: string;
		difficulty: number;
	};
	unlocked: boolean;
	completed: boolean;
	onSelect: () => void;
}) {
	return (
		<button
			type="button"
			disabled={!unlocked}
			aria-disabled={!unlocked}
			aria-label={`Scenario: ${scenario.title} - ${scenario.subtitle}`}
			onClick={() => unlocked && onSelect()}
			className={`relative w-full rounded-xl border-2 p-4 text-left transition ${
				unlocked ? 'cursor-pointer hover:-translate-y-0.5 hover:border-accent hover:shadow-card' : 'cursor-not-allowed opacity-60'
			} ${completed ? 'border-success bg-success-muted' : 'border-border bg-surface-2'} ${!unlocked ? 'grayscale-[0.3]' : ''}`}
		>
			<div className="mb-1 text-xs font-semibold uppercase tracking-wide text-accent">Level {scenario.difficulty}</div>
			<h4 className="m-0 mb-1 text-lg font-bold text-ink-1">{scenario.title}</h4>
			<p className="m-0 mb-2 text-sm leading-snug text-ink-2">{scenario.subtitle}</p>
			<div className="flex flex-wrap gap-2 text-xs text-ink-3">
				<span>BAC: ${scenario.bac.toLocaleString()}</span>
				<span>•</span>
				<span>{scenario.duration}</span>
			</div>
			{completed ? (
				<span className="absolute right-3 top-3 rounded bg-success px-2 py-1 text-xs font-semibold text-white">
					Complete
				</span>
			) : !unlocked ? (
				<span className="absolute right-3 top-3 rounded bg-surface-3 px-2 py-1 text-xs font-semibold text-ink-3">
					Locked
				</span>
			) : null}
		</button>
	);
}
