// evms-training/src/components/ThreadPicker.svelte
<script>
	import { learningThreads } from '../lib/threads/index.js';

	let { onSelectThread } = $props();
</script>

<section class="thread-picker" aria-labelledby="threads-heading">
	<div class="section-header">
		<h2 id="threads-heading">Choose a learning path</h2>
		<p class="section-desc">
			Recommended order on this page: EVMS 101 first, then Read the metrics (twelve cases), then Project scenarios for
			hands-on narratives.
		</p>
	</div>
	<div class="thread-cards">
		{#each learningThreads as thread (thread.id)}
			<button
				type="button"
				class="thread-card"
				class:variant-projects={thread.variant === 'projects'}
				class:variant-academic={thread.variant === 'academic'}
				class:variant-metrics={thread.variant === 'metrics'}
				onclick={() => onSelectThread?.(thread.id)}
				aria-label="Learning path: {thread.title} — {thread.subtitle}"
			>
				<span class="pill">{thread.subtitle}</span>
				<h3 class="thread-title">{thread.title}</h3>
				<p class="thread-desc">{thread.description}</p>
				<span class="cta">Open</span>
			</button>
		{/each}
	</div>
</section>

<style>
	.thread-picker {
		margin-bottom: var(--space-6);
	}

	.section-header {
		margin-bottom: var(--space-6);
	}

	.section-header h2 {
		margin: 0 0 var(--space-2);
		font-size: var(--text-2xl);
		font-weight: 700;
		color: var(--text-1);
	}

	.section-desc {
		margin: 0;
		font-size: var(--text-base);
		color: var(--text-2);
		line-height: 1.6;
		max-width: 65ch;
	}

	.thread-cards {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
		gap: var(--space-4);
	}

	.thread-card {
		position: relative;
		text-align: left;
		padding: var(--space-5);
		border-radius: var(--radius-lg);
		border: 2px solid var(--border);
		background: var(--surface-2);
		cursor: pointer;
		transition:
			border-color 0.2s,
			box-shadow 0.2s,
			transform 0.2s;
		display: flex;
		flex-direction: column;
		gap: var(--space-2);
		min-height: 200px;
	}

	.thread-card:hover {
		border-color: var(--accent);
		box-shadow: var(--shadow-md);
		transform: translateY(-2px);
	}

	.thread-card.variant-projects {
		border-left: 4px solid var(--accent);
	}

	.thread-card.variant-academic {
		border-left: 4px solid #6366f1;
	}

	.thread-card.variant-metrics {
		border-left: 4px solid #0d9488;
	}

	.pill {
		font-size: var(--text-xs);
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.06em;
		color: var(--text-3);
	}

	.thread-title {
		margin: 0;
		font-size: var(--text-xl);
		font-weight: 700;
		color: var(--text-1);
	}

	.thread-desc {
		margin: 0;
		flex: 1;
		font-size: var(--text-sm);
		color: var(--text-2);
		line-height: 1.55;
	}

	.cta {
		margin-top: var(--space-2);
		font-size: var(--text-sm);
		font-weight: 600;
		color: var(--accent);
	}
</style>

// evms-training/components/interactive/ThreadPicker.tsx
'use client';

import { learningThreads } from '@/lib/threads/index';

export function ThreadPicker({ onSelectThread }: { onSelectThread: (id: string) => void }) {
	return (
		<section className="mb-8" aria-labelledby="threads-heading">
			<div className="mb-6">
				<h2 id="threads-heading" className="text-2xl font-bold text-ink-1">
					Choose a learning path
				</h2>
				<p className="mt-2 max-w-prose text-base leading-relaxed text-ink-2">
					Recommended order on this page: EVMS 101 first, then Read the metrics (twelve cases), then Project
					scenarios for hands-on narratives.
				</p>
			</div>
			<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
				{learningThreads.map((thread) => (
					<button
						key={thread.id}
						type="button"
						onClick={() => onSelectThread(thread.id)}
						aria-label={`Learning path: ${thread.title} — ${thread.subtitle}`}
						className={`flex min-h-[12.5rem] flex-col gap-2 rounded-xl border-2 border-border bg-surface-2 p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-accent hover:shadow-card ${
							thread.variant === 'projects'
								? 'border-l-4 border-l-accent'
								: thread.variant === 'academic'
									? 'border-l-4 border-l-indigo-500'
									: 'border-l-4 border-l-teal-600'
						}`}
					>
						<span className="text-xs font-semibold uppercase tracking-wide text-ink-3">{thread.subtitle}</span>
						<h3 className="m-0 text-xl font-bold text-ink-1">{thread.title}</h3>
						<p className="m-0 flex-1 text-sm leading-relaxed text-ink-2">{thread.description}</p>
						<span className="mt-2 text-sm font-semibold text-accent">Open</span>
					</button>
				))}
			</div>
		</section>
	);
}
